"""empty message

Revision ID: 47a07ba31508
Revises: ba094d713491
Create Date: 2024-08-30 15:46:01.514145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a07ba31508'
down_revision = 'ba094d713491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commenter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['commenter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('commenter_id')

    # ### end Alembic commands ###
